
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qigmqsyfwsyqhnchlein.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZ21xc3lmd3N5cWhuY2hsZWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mzk0MjMsImV4cCI6MjA2NDMxNTQyM30.dQtP3s3cXWyRq5AUS9ef_DjnEbJ3RBElDxRLOU8nnaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
